### ISSUE TITLE
Update for ReSharper 2016.3

### ISSUE THREAD

**Issue by Drakmyth** [Drakmyth/ReSharperMacros#2]
ReSharper 2016.3 is released and requires an update for all extensions.

**Comment by garyng** [comment]
Any updates? 😄

**Comment by Drakmyth** [comment]
Haven't gotten a chance to look at this. ReSharper 2017.1 is in EAP now, and I was kind of planning on just waiting until that goes RTM then updating to that since it will probably require an update as well, but a rough estimate puts that another month out. I'll try see if I can make time to get this updated this weekend.

**Comment by Drakmyth** [comment]
Version 1.4.0 for ReSharper 2016.3 has released!
